# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{google_visualr}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["msalzburg"]
  s.date = %q{2010-07-11}
  s.description = %q{longer description of your gem}
  s.email = %q{salzburg@emjot.de}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/base_chart.rb",
     "lib/charts.rb",
     "lib/charts/image_area_chart.rb",
     "lib/charts/image_bar_chart.rb",
     "lib/charts/image_line_chart.rb",
     "lib/charts/image_pie_chart.rb",
     "lib/charts/image_spark_line.rb",
     "lib/data_table.rb",
     "lib/data_table/data_cell.rb",
     "lib/data_table/data_column.rb",
     "lib/data_table/data_row.rb",
     "lib/formatters.rb",
     "lib/formatters/arrow_format.rb",
     "lib/formatters/bar_format.rb",
     "lib/formatters/base_format.rb",
     "lib/formatters/color_format.rb",
     "lib/formatters/date_format.rb",
     "lib/formatters/number_format.rb",
     "lib/packages.rb",
     "lib/utilities.rb",
     "lib/utilities/attribute_reflection.rb",
     "lib/utilities/google_class_reflection.rb",
     "lib/utilities/google_package_reflection.rb",
     "lib/utilities/type_casting.rb",
     "lib/visualizations.rb",
     "lib/visualizations/annotated_time_line.rb",
     "lib/visualizations/area_chart.rb",
     "lib/visualizations/bar_chart.rb",
     "lib/visualizations/column_chart.rb",
     "lib/visualizations/gauge.rb",
     "lib/visualizations/geo_map.rb",
     "lib/visualizations/intensity_map.rb",
     "lib/visualizations/line_chart.rb",
     "lib/visualizations/map.rb",
     "lib/visualizations/motion_chart.rb",
     "lib/visualizations/org_chart.rb",
     "lib/visualizations/pie_chart.rb",
     "lib/visualizations/scatter_chart.rb",
     "lib/visualizations/table.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/msalzburg/google_visualr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/helper.rb",
     "test/test_google_visualr.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

